---
- hosts: all
  gather_facts: false
  become: true
  vars:
   companyName: MSS
   location: karnataka
  tasks:
   - name: Install Apache HTTP Server
     tags:
      - install
     yum:
      name: httpd
      state: latest
   - name: copy index.html
     tags:
      - copy
      - install
     copy:
      src: index.html
      dest: /var/www/html/index.html   
   - name: Start the Apache HTTP Server
     tags:
      - start
     service:
      name: httpd
      state: started
...
